version: '3.8'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.docker
    networks:
      - node
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    hostname: app
    container_name: app
    restart: always
    entrypoint: wait-for db:3306 -t 40 -- ./.docker/entrypoint.sh
    ports:
      - '3000:3000'
    volumes:
      - ./node:/home/node/app
    build:
      context: ./node/.docker
    tty: true
    networks:
      - node
    depends_on:
      - db
    command: npm start

  db:
    container_name: db
    restart: always
    image: mysql:5.7
    tty: true
    volumes:
      - ./mysql/.docker/database:/var/lib/mysql
      - ./mysql/.docker:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=fullcycle
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node

networks:
  node:
    driver: bridge
